export type Aircraft = {
  id: string;
  model: string;
  type: "commercial" | "military" | "vintage" | "general";
  wikiTitle?: string;
  fact: string;
  specs: {
    role: string;
    firstFlight?: string;
    engines?: string;
  };
};

export const AIRCRAFT_DB: Aircraft[] = [
  // Commercial
  {
    id: "b738",
    model: "Boeing 737-800",
    type: "commercial",
    wikiTitle: "Boeing 737 Next Generation",
    fact: "A best-selling narrow-body widely used on short and medium-haul routes.",
    specs: { role: "Narrow-body airliner", firstFlight: "1997", engines: "2 x CFM56" },
  },
  {
    id: "b38m",
    model: "Boeing 737 MAX 8",
    type: "commercial",
    wikiTitle: "Boeing 737 MAX",
    fact: "A re-engined 737 variant fitted with CFM LEAP-1B engines.",
    specs: { role: "Narrow-body airliner", firstFlight: "2016", engines: "2 x LEAP-1B" },
  },
  {
    id: "b752",
    model: "Boeing 757-200",
    type: "commercial",
    wikiTitle: "Boeing 757",
    fact: "Known for strong runway performance and a tall, narrow landing gear stance.",
    specs: { role: "Narrow-body airliner", firstFlight: "1982", engines: "2 x turbofan" },
  },
  {
    id: "b763",
    model: "Boeing 767-300ER",
    type: "commercial",
    wikiTitle: "Boeing 767",
    fact: "A twin-aisle long-range airliner often used for transatlantic services.",
    specs: { role: "Wide-body airliner", firstFlight: "1981", engines: "2 x turbofan" },
  },
  {
    id: "b744",
    model: "Boeing 747-400",
    type: "commercial",
    wikiTitle: "Boeing 747-400",
    fact: "The iconic Queen of the Skies has a distinctive hump-backed upper deck.",
    specs: { role: "Wide-body airliner", firstFlight: "1988", engines: "4 x turbofan" },
  },
  {
    id: "b77w",
    model: "Boeing 777-300ER",
    type: "commercial",
    wikiTitle: "Boeing 777",
    fact: "A long-range twinjet known for large GE90 engines and high efficiency.",
    specs: { role: "Wide-body airliner", firstFlight: "1994", engines: "2 x GE90-115B" },
  },
  {
    id: "b789",
    model: "Boeing 787-9",
    type: "commercial",
    wikiTitle: "Boeing 787 Dreamliner",
    fact: "A composite-rich Dreamliner variant with excellent range and cabin comfort.",
    specs: { role: "Wide-body airliner", firstFlight: "2013", engines: "2 x Trent 1000 or GEnx" },
  },
  {
    id: "a20n",
    model: "Airbus A320neo",
    type: "commercial",
    wikiTitle: "Airbus A320neo family",
    fact: "The neo family uses newer engines and wingtip devices to reduce fuel burn.",
    specs: { role: "Narrow-body airliner", firstFlight: "2014", engines: "2 x LEAP-1A or PW1100G" },
  },
  {
    id: "a21n",
    model: "Airbus A321neo",
    type: "commercial",
    wikiTitle: "Airbus A321neo",
    fact: "A stretched A320 family member popular for high-density and longer thin routes.",
    specs: { role: "Narrow-body airliner", firstFlight: "2016", engines: "2 x LEAP-1A or PW1100G" },
  },
  {
    id: "a332",
    model: "Airbus A330-200",
    type: "commercial",
    wikiTitle: "Airbus A330",
    fact: "A shorter A330 variant with long range and a wide-body twin-engine layout.",
    specs: { role: "Wide-body airliner", firstFlight: "1997", engines: "2 x turbofan" },
  },
  {
    id: "a339",
    model: "Airbus A330-900neo",
    type: "commercial",
    wikiTitle: "Airbus A330neo",
    fact: "A modernized A330 with new wings and Rolls-Royce Trent 7000 engines.",
    specs: { role: "Wide-body airliner", firstFlight: "2017", engines: "2 x Trent 7000" },
  },
  {
    id: "a359",
    model: "Airbus A350-900",
    type: "commercial",
    wikiTitle: "Airbus A350",
    fact: "An advanced composite twinjet with distinctive curved winglets.",
    specs: { role: "Wide-body airliner", firstFlight: "2013", engines: "2 x Trent XWB" },
  },
  {
    id: "a388",
    model: "Airbus A380-800",
    type: "commercial",
    wikiTitle: "Airbus A380",
    fact: "The world's largest passenger airliner has two full-length passenger decks.",
    specs: { role: "Very large airliner", firstFlight: "2005", engines: "4 x turbofan" },
  },
  {
    id: "e175",
    model: "Embraer E175",
    type: "commercial",
    wikiTitle: "Embraer E-Jet family",
    fact: "A popular regional jet with a comfortable two-by-two cabin layout.",
    specs: { role: "Regional jet", firstFlight: "2003", engines: "2 x CF34" },
  },
  {
    id: "e190e2",
    model: "Embraer E190-E2",
    type: "commercial",
    wikiTitle: "Embraer E-Jet E2 family",
    fact: "A second-generation E-Jet optimized for regional efficiency.",
    specs: { role: "Regional jet", firstFlight: "2016", engines: "2 x PW1900G" },
  },
  {
    id: "crj900",
    model: "Bombardier CRJ900",
    type: "commercial",
    wikiTitle: "Bombardier CRJ700 series",
    fact: "A stretched regional jet commonly seen on feeder routes.",
    specs: { role: "Regional jet", firstFlight: "2001", engines: "2 x CF34" },
  },
  {
    id: "atr726",
    model: "ATR 72-600",
    type: "commercial",
    wikiTitle: "ATR 72",
    fact: "A popular turboprop for short-haul regional routes.",
    specs: { role: "Regional turboprop", firstFlight: "2009", engines: "2 x PW127" },
  },
  {
    id: "q400",
    model: "De Havilland Canada Dash 8 Q400",
    type: "commercial",
    wikiTitle: "De Havilland Canada Dash 8",
    fact: "A fast regional turboprop with six-blade propellers.",
    specs: { role: "Regional turboprop", firstFlight: "1998", engines: "2 x PW150A" },
  },

  // Military
  {
    id: "f16",
    model: "F-16 Fighting Falcon",
    type: "military",
    wikiTitle: "General Dynamics F-16 Fighting Falcon",
    fact: "An agile multirole fighter famed for its bubble canopy and fly-by-wire controls.",
    specs: { role: "Multirole fighter", firstFlight: "1974", engines: "1 x turbofan" },
  },
  {
    id: "f15",
    model: "F-15 Eagle",
    type: "military",
    wikiTitle: "McDonnell Douglas F-15 Eagle",
    fact: "A twin-engine air-superiority fighter with a long combat record.",
    specs: { role: "Air-superiority fighter", firstFlight: "1972", engines: "2 x turbofan" },
  },
  {
    id: "f18",
    model: "F/A-18E Super Hornet",
    type: "military",
    wikiTitle: "Boeing F/A-18E/F Super Hornet",
    fact: "A carrier-capable strike fighter used by the United States Navy.",
    specs: { role: "Carrier multirole fighter", firstFlight: "1995", engines: "2 x turbofan" },
  },
  {
    id: "f22",
    model: "F-22 Raptor",
    type: "military",
    wikiTitle: "Lockheed Martin F-22 Raptor",
    fact: "A stealth air-superiority fighter with supercruise capability.",
    specs: { role: "Stealth fighter", firstFlight: "1997", engines: "2 x turbofan" },
  },
  {
    id: "f35",
    model: "F-35A Lightning II",
    type: "military",
    wikiTitle: "Lockheed Martin F-35 Lightning II",
    fact: "A fifth-generation stealth fighter with advanced sensor fusion.",
    specs: { role: "Stealth multirole fighter", firstFlight: "2006", engines: "1 x F135" },
  },
  {
    id: "a10",
    model: "A-10 Thunderbolt II",
    type: "military",
    wikiTitle: "Fairchild Republic A-10 Thunderbolt II",
    fact: "A close air support aircraft built around a powerful 30 mm cannon.",
    specs: { role: "Close air support", firstFlight: "1972", engines: "2 x turbofan" },
  },
  {
    id: "b2",
    model: "B-2 Spirit",
    type: "military",
    wikiTitle: "Northrop Grumman B-2 Spirit",
    fact: "A flying-wing stealth bomber designed to penetrate defended airspace.",
    specs: { role: "Stealth bomber", firstFlight: "1989", engines: "4 x turbofan" },
  },
  {
    id: "b52",
    model: "B-52 Stratofortress",
    type: "military",
    wikiTitle: "Boeing B-52 Stratofortress",
    fact: "A long-serving strategic bomber with eight engines mounted in four pods.",
    specs: { role: "Strategic bomber", firstFlight: "1952", engines: "8 x turbofan" },
  },
  {
    id: "c130j",
    model: "C-130J Super Hercules",
    type: "military",
    wikiTitle: "Lockheed Martin C-130J Super Hercules",
    fact: "A tactical airlifter renowned for short and rough-field performance.",
    specs: { role: "Tactical transport", firstFlight: "1996", engines: "4 x turboprop" },
  },
  {
    id: "c17",
    model: "C-17 Globemaster III",
    type: "military",
    wikiTitle: "Boeing C-17 Globemaster III",
    fact: "A large military transport designed for strategic and tactical airlift.",
    specs: { role: "Military transport", firstFlight: "1991", engines: "4 x turbofan" },
  },
  {
    id: "typhoon",
    model: "Eurofighter Typhoon",
    type: "military",
    wikiTitle: "Eurofighter Typhoon",
    fact: "A delta-canard multirole fighter developed by a European consortium.",
    specs: { role: "Multirole fighter", firstFlight: "1994", engines: "2 x turbofan" },
  },
  {
    id: "rafale",
    model: "Dassault Rafale",
    type: "military",
    wikiTitle: "Dassault Rafale",
    fact: "A highly agile French multirole fighter with carrier-capable variants.",
    specs: { role: "Multirole fighter", firstFlight: "1986", engines: "2 x turbofan" },
  },
  {
    id: "su27",
    model: "Sukhoi Su-27",
    type: "military",
    wikiTitle: "Sukhoi Su-27",
    fact: "A large twin-engine fighter recognized for its blended wing-body shape.",
    specs: { role: "Air-superiority fighter", firstFlight: "1977", engines: "2 x turbofan" },
  },
  {
    id: "mig29",
    model: "Mikoyan MiG-29",
    type: "military",
    wikiTitle: "Mikoyan MiG-29",
    fact: "A Soviet-designed fighter with widely spaced engines and high agility.",
    specs: { role: "Multirole fighter", firstFlight: "1977", engines: "2 x turbofan" },
  },
  {
    id: "uh60",
    model: "UH-60 Black Hawk",
    type: "military",
    wikiTitle: "Sikorsky UH-60 Black Hawk",
    fact: "A utility helicopter used for troop transport, rescue, and support missions.",
    specs: { role: "Utility helicopter", firstFlight: "1974", engines: "2 x turboshaft" },
  },

  // Vintage
  {
    id: "dc3",
    model: "Douglas DC-3",
    type: "vintage",
    wikiTitle: "Douglas DC-3",
    fact: "A 1930s airliner that helped make passenger air travel practical.",
    specs: { role: "Piston airliner", firstFlight: "1935", engines: "2 x radial" },
  },
  {
    id: "constellation",
    model: "Lockheed Constellation",
    type: "vintage",
    wikiTitle: "Lockheed Constellation",
    fact: "An elegant piston airliner known for its curved fuselage and triple tail.",
    specs: { role: "Piston airliner", firstFlight: "1943", engines: "4 x radial" },
  },
  {
    id: "707",
    model: "Boeing 707",
    type: "vintage",
    wikiTitle: "Boeing 707",
    fact: "An early successful jet airliner that popularized intercontinental jet travel.",
    specs: { role: "Jet airliner", firstFlight: "1957", engines: "4 x turbojet or turbofan" },
  },
  {
    id: "727",
    model: "Boeing 727",
    type: "vintage",
    wikiTitle: "Boeing 727",
    fact: "A three-engine jet airliner with a T-tail and rear-mounted engines.",
    specs: { role: "Trijet airliner", firstFlight: "1963", engines: "3 x turbofan" },
  },
  {
    id: "comet",
    model: "de Havilland Comet",
    type: "vintage",
    wikiTitle: "de Havilland Comet",
    fact: "The world's first commercial jet airliner reshaped aircraft fatigue design.",
    specs: { role: "Jet airliner", firstFlight: "1949", engines: "4 x turbojet" },
  },
  {
    id: "concorde",
    model: "Concorde",
    type: "vintage",
    wikiTitle: "Concorde",
    fact: "A supersonic airliner famous for its delta wing and droop nose.",
    specs: { role: "Supersonic airliner", firstFlight: "1969", engines: "4 x Olympus" },
  },
  {
    id: "spitfire",
    model: "Supermarine Spitfire",
    type: "vintage",
    wikiTitle: "Supermarine Spitfire",
    fact: "A World War II fighter famous for its elliptical wing planform.",
    specs: { role: "WWII fighter", firstFlight: "1936", engines: "1 x Merlin or Griffon" },
  },
  {
    id: "p51",
    model: "North American P-51 Mustang",
    type: "vintage",
    wikiTitle: "North American P-51 Mustang",
    fact: "A long-range World War II escort fighter renowned for speed and range.",
    specs: { role: "WWII fighter", firstFlight: "1940", engines: "1 x Merlin" },
  },
  {
    id: "b17",
    model: "Boeing B-17 Flying Fortress",
    type: "vintage",
    wikiTitle: "Boeing B-17 Flying Fortress",
    fact: "A four-engine heavy bomber used extensively during World War II.",
    specs: { role: "Heavy bomber", firstFlight: "1935", engines: "4 x radial" },
  },
  {
    id: "b29",
    model: "Boeing B-29 Superfortress",
    type: "vintage",
    wikiTitle: "Boeing B-29 Superfortress",
    fact: "An advanced World War II bomber with pressurized crew compartments.",
    specs: { role: "Heavy bomber", firstFlight: "1942", engines: "4 x radial" },
  },
  {
    id: "ju52",
    model: "Junkers Ju 52",
    type: "vintage",
    wikiTitle: "Junkers Ju 52",
    fact: "A corrugated-metal transport aircraft recognized by its three engines.",
    specs: { role: "Transport aircraft", firstFlight: "1930", engines: "3 x radial" },
  },
  {
    id: "an2",
    model: "Antonov An-2",
    type: "vintage",
    wikiTitle: "Antonov An-2",
    fact: "A rugged single-engine biplane used for utility and agricultural work.",
    specs: { role: "Utility biplane", firstFlight: "1947", engines: "1 x radial" },
  },

  // General aviation
  {
    id: "c172",
    model: "Cessna 172 Skyhawk",
    type: "general",
    wikiTitle: "Cessna 172",
    fact: "One of the most produced aircraft ever and a staple of flight training.",
    specs: { role: "GA trainer", firstFlight: "1955", engines: "1 x piston" },
  },
  {
    id: "c182",
    model: "Cessna 182 Skylane",
    type: "general",
    wikiTitle: "Cessna 182 Skylane",
    fact: "A four-seat single-engine aircraft known for useful load and versatility.",
    specs: { role: "General aviation", firstFlight: "1956", engines: "1 x piston" },
  },
  {
    id: "pa28",
    model: "Piper PA-28 Cherokee",
    type: "general",
    wikiTitle: "Piper PA-28 Cherokee",
    fact: "A widely used training and personal aircraft with low-mounted wings.",
    specs: { role: "GA trainer", firstFlight: "1960", engines: "1 x piston" },
  },
  {
    id: "sr22",
    model: "Cirrus SR22",
    type: "general",
    wikiTitle: "Cirrus SR22",
    fact: "A high-performance GA aircraft known for its whole-airframe parachute system.",
    specs: { role: "General aviation", firstFlight: "2000", engines: "1 x piston" },
  },
  {
    id: "kingair350",
    model: "Beechcraft King Air 350",
    type: "general",
    wikiTitle: "Beechcraft King Air",
    fact: "A popular twin-turboprop used for business, utility, and special missions.",
    specs: { role: "GA turboprop", firstFlight: "1988", engines: "2 x PT6A" },
  },
  {
    id: "pc12",
    model: "Pilatus PC-12",
    type: "general",
    wikiTitle: "Pilatus PC-12",
    fact: "A single-engine turboprop valued for short-field utility and cabin flexibility.",
    specs: { role: "Utility turboprop", firstFlight: "1991", engines: "1 x PT6A" },
  },
  {
    id: "tbm900",
    model: "Daher TBM 900",
    type: "general",
    wikiTitle: "Daher TBM 900",
    fact: "A fast single-engine turboprop with business-aircraft performance.",
    specs: { role: "Business turboprop", firstFlight: "2014", engines: "1 x PT6A" },
  },
  {
    id: "da42",
    model: "Diamond DA42 Twin Star",
    type: "general",
    wikiTitle: "Diamond DA42 Twin Star",
    fact: "A modern composite twin used for training and personal flying.",
    specs: { role: "GA twin", firstFlight: "2002", engines: "2 x diesel piston" },
  },
  {
    id: "be58",
    model: "Beechcraft Baron 58",
    type: "general",
    wikiTitle: "Beechcraft Baron",
    fact: "A classic light twin with a reputation for speed and solid handling.",
    specs: { role: "Light twin", firstFlight: "1969", engines: "2 x piston" },
  },
  {
    id: "mooney-m20",
    model: "Mooney M20",
    type: "general",
    wikiTitle: "Mooney M20",
    fact: "A sleek single-engine aircraft known for efficient speed.",
    specs: { role: "Personal aircraft", firstFlight: "1953", engines: "1 x piston" },
  },
  {
    id: "rv7",
    model: "Van's Aircraft RV-7",
    type: "general",
    wikiTitle: "Van's Aircraft RV-7",
    fact: "A popular kit-built sport aircraft with responsive handling.",
    specs: { role: "Homebuilt sport aircraft", firstFlight: "2001", engines: "1 x piston" },
  },
  {
    id: "pa46",
    model: "Piper PA-46 Malibu",
    type: "general",
    wikiTitle: "Piper PA-46",
    fact: "A pressurized single-engine aircraft often used for personal business travel.",
    specs: { role: "Pressurized GA aircraft", firstFlight: "1979", engines: "1 x piston or turboprop" },
  },
  // Expanded aircraft pool
  { id: "e190", model: "Embraer E190", type: "commercial", wikiTitle: "Embraer E-Jet family", fact: "A regional jet with a comfortable four-abreast cabin.", specs: { role: "Regional jet", firstFlight: "2004", engines: "2 x GE CF34" } },
  { id: "crj900", model: "Bombardier CRJ900", type: "commercial", wikiTitle: "Bombardier CRJ700 series", fact: "A stretched regional jet recognizable by its T-tail and rear engines.", specs: { role: "Regional jet", firstFlight: "2001", engines: "2 x CF34" } },
  { id: "atr72", model: "ATR 72", type: "commercial", wikiTitle: "ATR 72", fact: "A twin-turboprop commuter aircraft built for short regional routes.", specs: { role: "Turboprop airliner", firstFlight: "1988", engines: "2 x PW127" } },
  { id: "il76", model: "Ilyushin Il-76", type: "commercial", wikiTitle: "Ilyushin Il-76", fact: "A rugged high-wing cargo aircraft with four engines.", specs: { role: "Cargo aircraft", firstFlight: "1971", engines: "4 x turbofan" } },
  { id: "f15", model: "McDonnell Douglas F-15 Eagle", type: "military", wikiTitle: "McDonnell Douglas F-15 Eagle", fact: "A powerful twin-tail air-superiority fighter.", specs: { role: "Air-superiority fighter", firstFlight: "1972", engines: "2 x F100" } },
  { id: "f22", model: "Lockheed Martin F-22 Raptor", type: "military", wikiTitle: "Lockheed Martin F-22 Raptor", fact: "A stealth fighter combining supercruise, thrust vectoring, and agility.", specs: { role: "Stealth fighter", firstFlight: "1997", engines: "2 x F119" } },
  { id: "f35", model: "Lockheed Martin F-35 Lightning II", type: "military", wikiTitle: "Lockheed Martin F-35 Lightning II", fact: "A single-engine stealth fighter produced in three variants.", specs: { role: "Multirole stealth fighter", firstFlight: "2006", engines: "1 x F135" } },
  { id: "su57", model: "Sukhoi Su-57", type: "military", wikiTitle: "Sukhoi Su-57", fact: "A Russian twin-engine fighter with blended stealth shaping.", specs: { role: "Multirole fighter", firstFlight: "2010", engines: "2 x turbofan" } },
  { id: "mig29", model: "Mikoyan MiG-29", type: "military", wikiTitle: "Mikoyan MiG-29", fact: "A compact Soviet fighter with widely spaced engines and twin tails.", specs: { role: "Air-superiority fighter", firstFlight: "1977", engines: "2 x turbofan" } },
  { id: "a10", model: "Fairchild Republic A-10 Thunderbolt II", type: "military", wikiTitle: "Fairchild Republic A-10 Thunderbolt II", fact: "The famous ground-attack aircraft with twin engines mounted high on its rear fuselage.", specs: { role: "Close-air-support aircraft", firstFlight: "1972", engines: "2 x TF34" } },
  { id: "c17", model: "Boeing C-17 Globemaster III", type: "military", wikiTitle: "Boeing C-17 Globemaster III", fact: "A strategic airlifter with a high wing, T-tail, and rear loading ramp.", specs: { role: "Strategic airlifter", firstFlight: "1991", engines: "4 x F117" } },
  { id: "spitfire", model: "Supermarine Spitfire", type: "vintage", wikiTitle: "Supermarine Spitfire", fact: "Its elliptical wing is one of the most recognizable shapes in aviation.", specs: { role: "Fighter", firstFlight: "1936", engines: "1 x Merlin piston" } },
  { id: "me109", model: "Messerschmitt Bf 109", type: "vintage", wikiTitle: "Messerschmitt Bf 109", fact: "A compact fighter with a narrow fuselage and distinctive squared tail.", specs: { role: "Fighter", firstFlight: "1935", engines: "1 x piston" } },
  { id: "dc4", model: "Douglas DC-4", type: "vintage", wikiTitle: "Douglas DC-4", fact: "A four-engine piston airliner that helped establish long-distance routes.", specs: { role: "Piston airliner", firstFlight: "1938", engines: "4 x radial" } },
  { id: "beech18", model: "Beechcraft Model 18", type: "vintage", wikiTitle: "Beechcraft Model 18", fact: "A twin-engine utility aircraft used worldwide for decades.", specs: { role: "Utility aircraft", firstFlight: "1937", engines: "2 x radial" } },
  { id: "kingair350", model: "Beechcraft King Air 350", type: "general", wikiTitle: "Beechcraft Super King Air", fact: "A pressurized twin-turboprop with a tall tail and streamlined nacelles.", specs: { role: "Business turboprop", firstFlight: "1972", engines: "2 x PT6A" } },
  { id: "cirrus-sr22", model: "Cirrus SR22", type: "general", wikiTitle: "Cirrus SR22", fact: "A modern single-engine aircraft known for its whole-airframe parachute.", specs: { role: "Personal aircraft", firstFlight: "2001", engines: "1 x piston" } },
  { id: "tbm900", model: "Daher TBM 900", type: "general", wikiTitle: "Socata TBM", fact: "A fast pressurized single-engine turboprop with a sleek nose.", specs: { role: "High-performance turboprop", firstFlight: "1990", engines: "1 x PT6A" } },
  // More commercial aircraft
  { id: "b717", model: "Boeing 717", type: "commercial", wikiTitle: "Boeing 717", fact: "A compact rear-engined airliner with a distinctive T-tail.", specs: { role: "Regional airliner", firstFlight: "1998", engines: "2 x BR715" } },
  { id: "b727", model: "Boeing 727", type: "commercial", wikiTitle: "Boeing 727", fact: "A classic trijet recognizable by its center tail engine.", specs: { role: "Narrow-body airliner", firstFlight: "1963", engines: "3 x JT8D" } },
  { id: "b737-200", model: "Boeing 737-200", type: "commercial", wikiTitle: "Boeing 737", fact: "The original 737 has compact underwing engines and a short fuselage.", specs: { role: "Narrow-body airliner", firstFlight: "1967", engines: "2 x JT8D" } },
  { id: "b737-900", model: "Boeing 737-900ER", type: "commercial", wikiTitle: "Boeing 737 Next Generation", fact: "The longest Next Generation 737 variant.", specs: { role: "Narrow-body airliner", firstFlight: "2006", engines: "2 x CFM56" } },
  { id: "b747-8", model: "Boeing 747-8", type: "commercial", wikiTitle: "Boeing 747-8", fact: "The final 747 generation with a stretched fuselage and raked wingtips.", specs: { role: "Wide-body airliner", firstFlight: "2010", engines: "4 x GEnx" } },
  { id: "b777-200", model: "Boeing 777-200", type: "commercial", wikiTitle: "Boeing 777", fact: "The original 777 introduced a new generation of large twinjets.", specs: { role: "Wide-body airliner", firstFlight: "1994", engines: "2 x turbofan" } },
  { id: "b777x", model: "Boeing 777X", type: "commercial", wikiTitle: "Boeing 777X", fact: "A large twinjet with folding wingtips for airport compatibility.", specs: { role: "Wide-body airliner", firstFlight: "2020", engines: "2 x GE9X" } },
  { id: "b787-8", model: "Boeing 787-8", type: "commercial", wikiTitle: "Boeing 787 Dreamliner", fact: "The shortest Dreamliner variant with serrated engine nacelles.", specs: { role: "Wide-body airliner", firstFlight: "2009", engines: "2 x turbofan" } },
  { id: "a319", model: "Airbus A319", type: "commercial", wikiTitle: "Airbus A319", fact: "A shortened A320 family aircraft used on shorter routes.", specs: { role: "Narrow-body airliner", firstFlight: "1995", engines: "2 x turbofan" } },
  { id: "a318", model: "Airbus A318", type: "commercial", wikiTitle: "Airbus A318", fact: "The smallest member of the original A320 family.", specs: { role: "Narrow-body airliner", firstFlight: "2002", engines: "2 x turbofan" } },
  { id: "a321xlr", model: "Airbus A321XLR", type: "commercial", wikiTitle: "Airbus A321", fact: "A long-range single-aisle aircraft with extra fuel capacity.", specs: { role: "Long-range narrow-body", firstFlight: "2022", engines: "2 x turbofan" } },
  { id: "a340", model: "Airbus A340-300", type: "commercial", wikiTitle: "Airbus A340", fact: "A four-engine wide-body with a long slender fuselage.", specs: { role: "Wide-body airliner", firstFlight: "1991", engines: "4 x turbofan" } },
  { id: "a350-1000", model: "Airbus A350-1000", type: "commercial", wikiTitle: "Airbus A350", fact: "The longest A350 with an elegant swept wing.", specs: { role: "Wide-body airliner", firstFlight: "2016", engines: "2 x Trent XWB" } },
  { id: "a380f", model: "Airbus A380", type: "commercial", wikiTitle: "Airbus A380", fact: "The largest passenger airliner, with two full-length decks.", specs: { role: "Very large airliner", firstFlight: "2005", engines: "4 x turbofan" } },
  { id: "concorde", model: "Concorde", type: "commercial", wikiTitle: "Concorde", fact: "A supersonic passenger aircraft with a slender delta wing.", specs: { role: "Supersonic airliner", firstFlight: "1969", engines: "4 x Olympus" } },
  { id: "comac-c919", model: "COMAC C919", type: "commercial", wikiTitle: "Comac C919", fact: "A modern Chinese narrow-body competitor to the A320 and 737.", specs: { role: "Narrow-body airliner", firstFlight: "2017", engines: "2 x LEAP-1C" } },
  { id: "ssj100", model: "Sukhoi Superjet 100", type: "commercial", wikiTitle: "Sukhoi Superjet 100", fact: "A regional jet with a high-set tailplane and rear-mounted engines.", specs: { role: "Regional jet", firstFlight: "2008", engines: "2 x SaM146" } },
  { id: "dash8", model: "De Havilland Canada Dash 8", type: "commercial", wikiTitle: "De Havilland Canada Dash 8", fact: "A high-wing turboprop built for short regional flights.", specs: { role: "Turboprop airliner", firstFlight: "1983", engines: "2 x PW100" } },
  { id: "fokker100", model: "Fokker 100", type: "commercial", wikiTitle: "Fokker 100", fact: "A Dutch regional jet with rear engines and a T-tail.", specs: { role: "Regional jet", firstFlight: "1986", engines: "2 x Rolls-Royce Tay" } },
  // More military aircraft
  { id: "f14", model: "Grumman F-14 Tomcat", type: "military", wikiTitle: "Grumman F-14 Tomcat", fact: "A carrier fighter famous for variable-sweep wings.", specs: { role: "Carrier fighter", firstFlight: "1970", engines: "2 x TF30" } },
  { id: "f16", model: "General Dynamics F-16 Fighting Falcon", type: "military", wikiTitle: "General Dynamics F-16 Fighting Falcon", fact: "A lightweight fighter with a frameless bubble canopy and side intakes.", specs: { role: "Multirole fighter", firstFlight: "1974", engines: "1 x F110 or F100" } },
  { id: "f18", model: "McDonnell Douglas F/A-18 Hornet", type: "military", wikiTitle: "McDonnell Douglas F/A-18 Hornet", fact: "A twin-tail carrier fighter with prominent leading-edge extensions.", specs: { role: "Carrier multirole fighter", firstFlight: "1978", engines: "2 x F404" } },
  { id: "harrier", model: "Harrier", type: "military", wikiTitle: "Harrier (aircraft)", fact: "A combat jet capable of vertical and short takeoff and landing.", specs: { role: "V/STOL attack aircraft", firstFlight: "1960", engines: "1 x Pegasus" } },
  { id: "typhoon", model: "Eurofighter Typhoon", type: "military", wikiTitle: "Eurofighter Typhoon", fact: "A canard-delta fighter with close-coupled foreplanes.", specs: { role: "Multirole fighter", firstFlight: "1994", engines: "2 x EJ200" } },
  { id: "rafale", model: "Dassault Rafale", type: "military", wikiTitle: "Dassault Rafale", fact: "A French delta-canard multirole fighter.", specs: { role: "Multirole fighter", firstFlight: "1986", engines: "2 x M88" } },
  { id: "mirage2000", model: "Dassault Mirage 2000", type: "military", wikiTitle: "Dassault Mirage 2000", fact: "A single-engine delta-wing fighter with a clean triangular planform.", specs: { role: "Multirole fighter", firstFlight: "1978", engines: "1 x M53" } },
  { id: "mirageiii", model: "Dassault Mirage III", type: "military", wikiTitle: "Dassault Mirage III", fact: "A classic supersonic delta-wing fighter.", specs: { role: "Interceptor", firstFlight: "1956", engines: "1 x Atar" } },
  { id: "jaguar", model: "SEPECAT Jaguar", type: "military", wikiTitle: "SEPECAT Jaguar", fact: "A low-level strike aircraft with twin engines and a slim fuselage.", specs: { role: "Attack aircraft", firstFlight: "1968", engines: "2 x Adour" } },
  { id: "tornado", model: "Panavia Tornado", type: "military", wikiTitle: "Panavia Tornado", fact: "A swing-wing aircraft designed for low-level strike missions.", specs: { role: "Strike aircraft", firstFlight: "1974", engines: "2 x RB199" } },
  { id: "t50", model: "North American T-6 Texan", type: "military", wikiTitle: "North American T-6 Texan", fact: "A widely used advanced trainer with a radial engine.", specs: { role: "Trainer aircraft", firstFlight: "1935", engines: "1 x radial" } },
  { id: "yak130", model: "Yakovlev Yak-130", type: "military", wikiTitle: "Yakovlev Yak-130", fact: "A modern twin-engine advanced jet trainer.", specs: { role: "Jet trainer", firstFlight: "1996", engines: "2 x turbofan" } },
  { id: "tu160", model: "Tupolev Tu-160", type: "military", wikiTitle: "Tupolev Tu-160", fact: "A huge supersonic bomber with variable-sweep wings.", specs: { role: "Strategic bomber", firstFlight: "1981", engines: "4 x turbofan" } },
  { id: "tu95", model: "Tupolev Tu-95", type: "military", wikiTitle: "Tupolev Tu-95", fact: "A long-range bomber powered by four enormous contra-rotating propellers.", specs: { role: "Strategic bomber", firstFlight: "1952", engines: "4 x turboprop" } },
  { id: "b52", model: "Boeing B-52 Stratofortress", type: "military", wikiTitle: "Boeing B-52 Stratofortress", fact: "A long-serving bomber with eight engines under a swept wing.", specs: { role: "Strategic bomber", firstFlight: "1952", engines: "8 x turbofan" } },
  { id: "b1b", model: "Rockwell B-1B Lancer", type: "military", wikiTitle: "Rockwell B-1 Lancer", fact: "A supersonic bomber with variable-sweep wings.", specs: { role: "Strategic bomber", firstFlight: "1974", engines: "4 x turbofan" } },
  { id: "ac130", model: "Lockheed AC-130", type: "military", wikiTitle: "Lockheed AC-130", fact: "A heavily armed gunship based on a transport aircraft.", specs: { role: "Gunship", firstFlight: "1966", engines: "4 x turboprop" } },
  { id: "c130", model: "Lockheed C-130 Hercules", type: "military", wikiTitle: "Lockheed C-130 Hercules", fact: "A rugged turboprop transport with a high wing and rear ramp.", specs: { role: "Tactical airlifter", firstFlight: "1954", engines: "4 x turboprop" } },
  { id: "c5", model: "Lockheed C-5 Galaxy", type: "military", wikiTitle: "Lockheed C-5 Galaxy", fact: "A massive strategic airlifter with a distinctive high T-tail.", specs: { role: "Strategic airlifter", firstFlight: "1968", engines: "4 x turbofan" } },
  { id: "v22", model: "Bell Boeing V-22 Osprey", type: "military", wikiTitle: "Bell Boeing V-22 Osprey", fact: "A tiltrotor whose engine nacelles rotate between flight modes.", specs: { role: "Tiltrotor transport", firstFlight: "1989", engines: "2 x T406" } },
  { id: "apache", model: "Boeing AH-64 Apache", type: "military", wikiTitle: "Boeing AH-64 Apache", fact: "An attack helicopter with tandem seats and a nose-mounted sensor turret.", specs: { role: "Attack helicopter", firstFlight: "1975", engines: "2 x turboshaft" } },
  { id: "blackhawk", model: "Sikorsky UH-60 Black Hawk", type: "military", wikiTitle: "Sikorsky UH-60 Black Hawk", fact: "A twin-engine utility helicopter with a recognizable angled tail boom.", specs: { role: "Utility helicopter", firstFlight: "1974", engines: "2 x turboshaft" } },
  { id: "chinook", model: "Boeing CH-47 Chinook", type: "military", wikiTitle: "Boeing CH-47 Chinook", fact: "A tandem-rotor heavy-lift helicopter.", specs: { role: "Heavy-lift helicopter", firstFlight: "1961", engines: "2 x turboshaft" } },
  { id: "cobra", model: "Bell AH-1 Cobra", type: "military", wikiTitle: "Bell AH-1 Cobra", fact: "A slim tandem-seat attack helicopter developed from the Huey.", specs: { role: "Attack helicopter", firstFlight: "1965", engines: "1 x turboshaft" } },
  // More vintage aircraft
  { id: "dc3", model: "Douglas DC-3", type: "vintage", wikiTitle: "Douglas DC-3", fact: "A legendary twin-engine airliner that transformed commercial aviation.", specs: { role: "Piston airliner", firstFlight: "1935", engines: "2 x radial" } },
  { id: "dc6", model: "Douglas DC-6", type: "vintage", wikiTitle: "Douglas DC-6", fact: "A polished four-engine piston airliner from the postwar era.", specs: { role: "Piston airliner", firstFlight: "1946", engines: "4 x radial" } },
  { id: "constellation", model: "Lockheed Constellation", type: "vintage", wikiTitle: "Lockheed Constellation", fact: "A graceful airliner with triple tail and curved fuselage.", specs: { role: "Piston airliner", firstFlight: "1943", engines: "4 x radial" } },
  { id: "dc10", model: "McDonnell Douglas DC-10", type: "vintage", wikiTitle: "McDonnell Douglas DC-10", fact: "A wide-body trijet with a tail-mounted center engine.", specs: { role: "Wide-body airliner", firstFlight: "1970", engines: "3 x turbofan" } },
  { id: "l1011", model: "Lockheed L-1011 TriStar", type: "vintage", wikiTitle: "Lockheed L-1011 TriStar", fact: "A wide-body trijet with a distinctive S-shaped center intake.", specs: { role: "Wide-body airliner", firstFlight: "1970", engines: "3 x turbofan" } },
  { id: "707", model: "Boeing 707", type: "vintage", wikiTitle: "Boeing 707", fact: "The jetliner that helped usher in the age of mass air travel.", specs: { role: "Jet airliner", firstFlight: "1957", engines: "4 x turbojet" } },
  { id: "caravelle", model: "Sud Aviation Caravelle", type: "vintage", wikiTitle: "Sud Aviation Caravelle", fact: "An early rear-engined jet with cockpit windows shaped like eyebrows.", specs: { role: "Jet airliner", firstFlight: "1955", engines: "2 x turbojet" } },
  { id: "comet", model: "de Havilland Comet", type: "vintage", wikiTitle: "de Havilland Comet", fact: "The world's first production jet airliner.", specs: { role: "Jet airliner", firstFlight: "1949", engines: "4 x turbojet" } },
  { id: "p51", model: "North American P-51 Mustang", type: "vintage", wikiTitle: "North American P-51 Mustang", fact: "A fast long-range fighter with a distinctive radiator scoop.", specs: { role: "Fighter", firstFlight: "1940", engines: "1 x Merlin piston" } },
  { id: "p38", model: "Lockheed P-38 Lightning", type: "vintage", wikiTitle: "Lockheed P-38 Lightning", fact: "A twin-boom fighter with twin engines and a central cockpit pod.", specs: { role: "Fighter", firstFlight: "1939", engines: "2 x Allison piston" } },
  { id: "p47", model: "Republic P-47 Thunderbolt", type: "vintage", wikiTitle: "Republic P-47 Thunderbolt", fact: "A large radial-engine fighter known for ruggedness.", specs: { role: "Fighter-bomber", firstFlight: "1941", engines: "1 x radial" } },
  { id: "avro-lancaster", model: "Avro Lancaster", type: "vintage", wikiTitle: "Avro Lancaster", fact: "A four-engine bomber with a clean, narrow fuselage.", specs: { role: "Heavy bomber", firstFlight: "1941", engines: "4 x Merlin piston" } },
  { id: "ju52", model: "Junkers Ju 52", type: "vintage", wikiTitle: "Junkers Ju 52", fact: "A corrugated-metal transport with three radial engines.", specs: { role: "Transport aircraft", firstFlight: "1930", engines: "3 x radial" } },
  { id: "fokker-dr1", model: "Fokker Dr.I", type: "vintage", wikiTitle: "Fokker Dr.I", fact: "A compact World War I triplane fighter.", specs: { role: "Fighter", firstFlight: "1917", engines: "1 x rotary" } },
  { id: "camel", model: "Sopwith Camel", type: "vintage", wikiTitle: "Sopwith Camel", fact: "A famous World War I biplane with twin synchronized guns.", specs: { role: "Fighter", firstFlight: "1916", engines: "1 x rotary" } },
  // More general aviation
  { id: "c150", model: "Cessna 150", type: "general", wikiTitle: "Cessna 150", fact: "A forgiving two-seat trainer found at flying schools worldwide.", specs: { role: "Trainer aircraft", firstFlight: "1957", engines: "1 x piston" } },
  { id: "c182", model: "Cessna 182 Skylane", type: "general", wikiTitle: "Cessna 182", fact: "A high-wing four-seat aircraft with strong short-field performance.", specs: { role: "General aviation", firstFlight: "1955", engines: "1 x piston" } },
  { id: "c206", model: "Cessna 206", type: "general", wikiTitle: "Cessna 206", fact: "A practical high-wing utility aircraft with a large cabin.", specs: { role: "Utility aircraft", firstFlight: "1962", engines: "1 x piston" } },
  { id: "c208", model: "Cessna 208 Caravan", type: "general", wikiTitle: "Cessna 208 Caravan", fact: "A rugged single-engine turboprop used for cargo and regional work.", specs: { role: "Utility turboprop", firstFlight: "1982", engines: "1 x PT6A" } },
  { id: "piper-pa28", model: "Piper PA-28 Cherokee", type: "general", wikiTitle: "Piper PA-28 Cherokee", fact: "A low-wing trainer with a simple, familiar silhouette.", specs: { role: "Trainer aircraft", firstFlight: "1960", engines: "1 x piston" } },
  { id: "piper-cub", model: "Piper J-3 Cub", type: "general", wikiTitle: "Piper J-3 Cub", fact: "A lightweight taildragger that defined the classic trainer airplane.", specs: { role: "Light aircraft", firstFlight: "1938", engines: "1 x piston" } },
  { id: "diamond-da40", model: "Diamond DA40", type: "general", wikiTitle: "Diamond DA40", fact: "A modern composite trainer with a high visibility canopy.", specs: { role: "Trainer aircraft", firstFlight: "1997", engines: "1 x piston" } },
  { id: "extra-300", model: "Extra 300", type: "general", wikiTitle: "Extra 300", fact: "An aerobatic aircraft with a strong symmetrical wing.", specs: { role: "Aerobatic aircraft", firstFlight: "1988", engines: "1 x piston" } },
  { id: "pc12", model: "Pilatus PC-12", type: "general", wikiTitle: "Pilatus PC-12", fact: "A versatile single-engine turboprop with a large cargo door.", specs: { role: "Utility turboprop", firstFlight: "1991", engines: "1 x PT6A" } },
  { id: "pc24", model: "Pilatus PC-24", type: "general", wikiTitle: "Pilatus PC-24", fact: "A business jet designed to use short and unpaved runways.", specs: { role: "Light business jet", firstFlight: "2013", engines: "2 x turbofan" } },
  { id: "learjet35", model: "Learjet 35", type: "general", wikiTitle: "Learjet 35", fact: "A classic light business jet with rear-mounted engines.", specs: { role: "Business jet", firstFlight: "1973", engines: "2 x turbofan" } },
  { id: "gulfstream-g650", model: "Gulfstream G650", type: "general", wikiTitle: "Gulfstream G650", fact: "A large business jet with swept wings and oval windows.", specs: { role: "Long-range business jet", firstFlight: "2009", engines: "2 x turbofan" } },
  { id: "phenom300", model: "Embraer Phenom 300", type: "general", wikiTitle: "Embraer Phenom 300", fact: "A popular light jet with a swept tail and rear engines.", specs: { role: "Light business jet", firstFlight: "2009", engines: "2 x turbofan" } },
  { id: "searey", model: "Progressive Aerodyne SeaRey", type: "general", wikiTitle: "Progressive Aerodyne SeaRey", fact: "An amphibious light aircraft with a pusher propeller.", specs: { role: "Amphibious aircraft", firstFlight: "1992", engines: "1 x piston" } },
];

export const TYPES: Array<Aircraft["type"]> = [
  "commercial",
  "military",
  "vintage",
  "general",
];
